[manager]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = true
sort_sensitive = false
show_hidden = true
wrap = "no"

[opener]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "linux" }
]

edit = [
	{ run = '$EDITOR "$@"', block = true, orphan = true, for = "linux" }
]

open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
