theme = "Catppuccin-mocha"
client_id = "58fb60b639564690b887ff1b726cc47d"
tracks_playback_limit = 50
playback_format = "{status} {track} • {artists}\n{album}\n{metadata}"
app_refresh_duration_in_ms = 16
page_size_in_rows = 32
enable_media_control = true
enable_streaming = "Always"
enable_notify = false
enable_cover_image_cache = true
default_device = "spotify-player"
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
cover_img_length = 16
cover_img_width = 7
seek_duration_secs = 5

[device]
name = "spotify-player"
device_type = "speaker"
volume = 50
bitrate = 320
audio_cache = true
normalization = false
autoplay = false

[layout]
library = { playlist_percent = 40, album_percent = 40 }
playback_window_position = "Top"
playback_window_height = 6
