theme = "Catppuccin-mocha"
tracks_playback_limit = 50
playback_format = "{status} {track} • {artists}\n{album}\n{metadata}"
notify_format = { summary = "{track} • {artists}", body = "{album}" }
notify_timeout_in_secs = 0
app_refresh_duration_in_ms = 16
playback_refresh_duration_in_ms = 0
page_size_in_rows = 32
enable_media_control = false
enable_streaming = "Always"
enable_notify = false
enable_cover_image_cache = true
notify_streaming_only = false
default_device = "spotify-player"
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
cover_img_length = 16
cover_img_width = 7
seek_duration_secs = 5

[device]
name = "spotify-player"
device_type = "speaker"
volume = 75
bitrate = 320
audio_cache = true
normalization = false
autoplay = false

[layout]
library = { playlist_percent = 40, album_percent = 40 }
playback_window_position = "Top"
playback_window_height = 6
