[[keymaps]]
command = "LikedTrackPage"
key_sequence = "l"

[[keymaps]]
command = "LyricsPage"
key_sequence = "z"

[[keymaps]]
command = "Repeat"
key_sequence = "r"

[[keymaps]]
command = "SearchPage"
key_sequence = "s"

[[keymaps]]
command = "SwitchDevice"
key_sequence = "d"

[[keymaps]]
command = "ShowActionsOnSelectedItem"
key_sequence = "a"

[[keymaps]]
command = "FocusNextWindow"
key_sequence = "tab"

[[keymaps]]
command = { VolumeChange = { offset = 5 } }
key_sequence = "="

[[keymaps]]
command = { VolumeChange = { offset = -5 } }
key_sequence = "-"
